language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script: pytest -v
deploy:
  provider: pypi
  user: "PPACI"
  password:
    secure: "YmQEacqn3+6K1vT9AEfxgYGMcqCMkPlyMdeNR5nBOD58bKYZYh5DJfVQQtVMfuQj4cY1052Go+oFPFgaga2eJMf19cKdht9GOhLna7NGsHjB2M+QlCNmMNgR616JlVnw7gHreF2HGbFZr0ujU4e2VLYS0iXdPPIEbNZ63VbCT9PowpBA6TMBnD6BpkeLj9fO4M6+5fHjc6guaLZpDcCpWgKcOsl8eegspa0HW0n3iZcgJ+/ikC4ZmZQ2V8VxeIeHHvhoD27FbPGb2J/EgPFtGg10qvSHm4qiVnrYuHqOztVhjja8jWJovNfdKqDnpOqsGT2rTmxFvloSpp4JAnzK9dn9NrRKw/1E/9VDvz0sd054iHYoS/rsOR3XnEmovdh+gED0qCDHtkiOYVSs16VVmnLpkRIpjUbLCaLHaBNYnerWUj+vzssAyOo6ryArjztvPNAJpVrb6dRowGCjy0sEX4vtD2E75sslXobOeyyYQPhoUkVD07ffZ8giBtk1wf8VUQQ4BFmT1NTzmRSZTbDG0+KWMHzYoiRBNaKCtyeaRlgnOem7lO8Lwse6baf/bG+wPqEdw+SZo8wpfW8Chk4eB4mae17C7fElBu7xWuDVAd9qsTvxHzUXn9pf899AVJqYOyXqIth+1rbV6pjagjUMmL9a+xYOeIX8h3oyik8mqrM="
  on:
    tags: true